// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        (unknown)
// source: capabilities/v1/capabilities.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// All the capabilities a plugin could have
type Capability int32

const (
	Capability_DATA         Capability = 0
	Capability_BLOCK        Capability = 1
	Capability_PAGE         Capability = 2
	Capability_CREATE_ISSUE Capability = 3
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "DATA",
		1: "BLOCK",
		2: "PAGE",
		3: "CREATE_ISSUE",
	}
	Capability_value = map[string]int32{
		"DATA":         0,
		"BLOCK":        1,
		"PAGE":         2,
		"CREATE_ISSUE": 3,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_capabilities_v1_capabilities_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_capabilities_v1_capabilities_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_capabilities_v1_capabilities_proto_rawDescGZIP(), []int{0}
}

type PluginCapabilities struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Capabilities []Capability `protobuf:"varint,1,rep,packed,name=capabilities,proto3,enum=Capability" json:"capabilities,omitempty"`
}

func (x *PluginCapabilities) Reset() {
	*x = PluginCapabilities{}
	if protoimpl.UnsafeEnabled {
		mi := &file_capabilities_v1_capabilities_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PluginCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginCapabilities) ProtoMessage() {}

func (x *PluginCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v1_capabilities_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginCapabilities.ProtoReflect.Descriptor instead.
func (*PluginCapabilities) Descriptor() ([]byte, []int) {
	return file_capabilities_v1_capabilities_proto_rawDescGZIP(), []int{0}
}

func (x *PluginCapabilities) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type GetCapabilitiesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
}

func (x *GetCapabilitiesRequest) Reset() {
	*x = GetCapabilitiesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_capabilities_v1_capabilities_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesRequest) ProtoMessage() {}

func (x *GetCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v1_capabilities_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_capabilities_v1_capabilities_proto_rawDescGZIP(), []int{1}
}

func (x *GetCapabilitiesRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

type GetCapabilitiesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success      bool                `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message      string              `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Capabilities *PluginCapabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
}

func (x *GetCapabilitiesResponse) Reset() {
	*x = GetCapabilitiesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_capabilities_v1_capabilities_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCapabilitiesResponse) ProtoMessage() {}

func (x *GetCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_capabilities_v1_capabilities_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_capabilities_v1_capabilities_proto_rawDescGZIP(), []int{2}
}

func (x *GetCapabilitiesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCapabilitiesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetCapabilitiesResponse) GetCapabilities() *PluginCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

var File_capabilities_v1_capabilities_proto protoreflect.FileDescriptor

var file_capabilities_v1_capabilities_proto_rawDesc = []byte{
	0x0a, 0x22, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x76,
	0x31, 0x2f, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x12, 0x50, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x2f, 0x0a, 0x0c, 0x63, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x52, 0x0c, 0x63,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x35, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x75, 0x67, 0x69, 0x6e,
	0x49, 0x64, 0x22, 0x86, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69,
	0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x63, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x50, 0x6c, 0x75, 0x67, 0x69,
	0x6e, 0x43, 0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x52, 0x0c, 0x63,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2a, 0x3d, 0x0a, 0x0a, 0x43,
	0x61, 0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x41, 0x54,
	0x41, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x08,
	0x0a, 0x04, 0x50, 0x41, 0x47, 0x45, 0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x43, 0x52, 0x45, 0x41,
	0x54, 0x45, 0x5f, 0x49, 0x53, 0x53, 0x55, 0x45, 0x10, 0x03, 0x42, 0x3e, 0x42, 0x11, 0x43, 0x61,
	0x70, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x6f,
	0x72, 0x74, 0x61, 0x6e, 0x69, 0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x63, 0x61, 0x70, 0x61, 0x62,
	0x69, 0x6c, 0x69, 0x74, 0x69, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_capabilities_v1_capabilities_proto_rawDescOnce sync.Once
	file_capabilities_v1_capabilities_proto_rawDescData = file_capabilities_v1_capabilities_proto_rawDesc
)

func file_capabilities_v1_capabilities_proto_rawDescGZIP() []byte {
	file_capabilities_v1_capabilities_proto_rawDescOnce.Do(func() {
		file_capabilities_v1_capabilities_proto_rawDescData = protoimpl.X.CompressGZIP(file_capabilities_v1_capabilities_proto_rawDescData)
	})
	return file_capabilities_v1_capabilities_proto_rawDescData
}

var file_capabilities_v1_capabilities_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_capabilities_v1_capabilities_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_capabilities_v1_capabilities_proto_goTypes = []interface{}{
	(Capability)(0),                 // 0: Capability
	(*PluginCapabilities)(nil),      // 1: PluginCapabilities
	(*GetCapabilitiesRequest)(nil),  // 2: GetCapabilitiesRequest
	(*GetCapabilitiesResponse)(nil), // 3: GetCapabilitiesResponse
}
var file_capabilities_v1_capabilities_proto_depIdxs = []int32{
	0, // 0: PluginCapabilities.capabilities:type_name -> Capability
	1, // 1: GetCapabilitiesResponse.capabilities:type_name -> PluginCapabilities
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_capabilities_v1_capabilities_proto_init() }
func file_capabilities_v1_capabilities_proto_init() {
	if File_capabilities_v1_capabilities_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_capabilities_v1_capabilities_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PluginCapabilities); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_capabilities_v1_capabilities_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapabilitiesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_capabilities_v1_capabilities_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCapabilitiesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_capabilities_v1_capabilities_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_capabilities_v1_capabilities_proto_goTypes,
		DependencyIndexes: file_capabilities_v1_capabilities_proto_depIdxs,
		EnumInfos:         file_capabilities_v1_capabilities_proto_enumTypes,
		MessageInfos:      file_capabilities_v1_capabilities_proto_msgTypes,
	}.Build()
	File_capabilities_v1_capabilities_proto = out.File
	file_capabilities_v1_capabilities_proto_rawDesc = nil
	file_capabilities_v1_capabilities_proto_goTypes = nil
	file_capabilities_v1_capabilities_proto_depIdxs = nil
}
